development:
  sessions:
    default:
      database: morning-pages-me_development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: morning-pages-me_test
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
